package com.tencent.p014mm.vfs;

import com.google.android.gms.measurement.AppMeasurement;
import com.google.firebase.analytics.FirebaseAnalytics;
import com.tencent.tinker.loader.shareutil.ShareConstants;
import com.tencent.xweb.xwalk.plugin.XWalkPlugin;
import org.xwalk.core.XWalkEnvironment;

/* renamed from: com.tencent.mm.vfs.k1 */
public class C116307k1 {

    /* renamed from: a */
    public static final String[] f349022a = {"app_xwalk_*", "app_webview_com_tencent_mm*", "app_hws_webview_com_tencent_mm*", "files", XWalkPlugin.PRIVATE_CACHE_DIR_NAME, "scan_goods", "shared_prefs", "app_xwalkplugin", "databases", XWalkEnvironment.MODULE_APPBRAND, "face_detect", "app_font", "app_tbs", ".auth_cache", "app_xwalkconfig", "app_turingdfp", ShareConstants.PATCH_DIRECTORY_NAME, "app_turingfd", ShareConstants.PATCH_TEMP_DIRECTORY_NAME, "extqbar", "app_tbs_common_share", "app_sslcache", "app_tbs_64", "app_qmsp", "cert", "app_x5webview", "app_webview", "no_backup", "app_execdir", "app_midasplugins", "app_midaslib_1", "lib", "huaweiks", "ilink", "xweb_lock", "app_dynamic_jar_output", "app_midaslib_0", "app_turingsmi", "code_cache", "openvoice", "app_.patch", "app_midasodex", ShareConstants.PATCH_DIRECTORY_NAME_SPEC, "app_expose", "app_icon_assets", "app_aimodel", "app_txsdklog", "fileshost", "shaders", "app_turingmm", "app_filelock", "app_recovery_lib", "app_tencentMapTemp", "app_flutter", "app_ringtone", "app_vibrate", "app_voip", "app_debugtbs", "app_exp_assets", "_hwclone", "app_TBSqmsp", "PluginInfo", ".magic_cache", "app_plugins", ShareConstants.ANDROID_O_DEX_OPTIMIZE_PATH, "app_dex", "dumptextures", "ex_libs", "Flyme_Clone", "voice_split_joint", "app_videoDexOutput", "Micrcrsgappbrand", "app_databases", "app_patch_res", "app_unlzma", "AssetsLibs", "app_one_time", "app_shoot_res", "filesm", "MicroMsg", "MicroMsg/${account}", "MicroMsg/WebNetFile", "aaTempPho"};

    /* renamed from: b */
    public static final String[] f349023b = {"webview_com_tencent_mm*", "old_org.chromium.android_webview*", "old_com.tencent.mm.xweb*", "websearch", "WebView", "org.chromium.xwalk", "mv_video", "wakelock", "wordBank", "LocalCache", "fts", "webprefetch", "webprefetch/resource", "TPReportCache_key", "oneday", "temp", "webprefetch/manifest", "webprefetch/content", "xnn", "com.tencent.mm.xweb", "topstory", "org.chromium.android_webview", "sticker", "beacon_volley", "box_temp", XWalkEnvironment.MODULE_APPBRAND, "cpsafe", "HttpCache", "image_search_temp", "image_search_temp", "mux", "recovery", "customcache", "WebNetFile", "imagecache", "MixAudio", "Data", "flutter", "tencent", ".db", "libCachedImageData", ShareConstants.ANDROID_O_DEX_OPTIMIZE_PATH, "webviewCacheChromium", "TextStatus", "aaTempPho", "mbEmbedPkgCache"};

    /* renamed from: c */
    public static final String[] f349024c = {"${accountSd}/image", "${accountSd}/favorite", "${accountSd}/oneday", "${accountSd}/emoji", "${accountSd}/voice2", "wxacache", "${accountSd}/bizimg", "${accountSd}/package", "wxanewfiles", "${accountSd}/video", "wxafiles", "${accountSd}/textstatus", "CheckResUpdate", "xlog", "vusericon", "Download", "card", "${accountSd}/mailapp", "${accountSd}/taskbar", "${accountSd}/recbiz", "Game", "mapsdk", "wallet", "recovery", "${accountSd}/image2", "${accountSd}/image2", ".tmp", "${accountSd}/music", "${accountSd}/record", "${accountSd}/attachment", "wagamefiles", "wallet_images", AppMeasurement.CRASH_ORIGIN, "${accountSd}/scanner", "${accountSd}/openim", "${accountSd}/favoffline", "FailMsgFileCache", "facedir", "SQLTrace", "hilive", "hbstoryvideo", "${accountSd}/openapi", "${accountSd}/boots", "${accountSd}/story", "${accountSd}/remark", "${accountSd}/dbback", "game", "${accountSd}/gamelife", "${accountSd}/gamelife/avatar", "wallet/images", "exdevice", "${accountSd}/shakemusic", "wxvideocache", "mail", "${accountSd}/multitask", "taxi_icon", "avatar", "browser", "${accountSd}/selectrecord", "${accountSd}/live", "fts", "AudioRecord", "${accountSd}/videovideoCompressTmpThumb", "${accountSd}/subvideo", "wepkg", "${accountSd}/draft", "${accountSd}/audio", "${accountSd}/videovideoCompressTmp", "${accountSd}", "Handler", "${accountSd}/bizmsg", "ThumbVideoCache", "${accountSd}/voice", "WebviewCache", "temp_video_cache", "${accountSd}/ProcessDetect", "diskcache", "wxvideotmp", "wenote", "${accountSd}/sfs", "video", "imagecache", "Diagnostic", "egg_spring", "${accountSd}/patmsg", XWalkEnvironment.MODULE_APPBRAND, "music", "wxauto", "wvtemp", "${accountSd}/cdn", "${accountSd}/secdata", "ClickFlow", "trace", "webcompt", "${accountSd}/LuckyMoney", "${accountSd}/game", "${accountSd}/syncFile", "ProcessDetector", "WebCanvasPkg", "download", "last_avatar_dir", "regioncode", "webview_tmpl", "${accountSd}/appbrand", "${accountSd}/normsg", "${accountSd}/wenote", ".planCache", "CheckResUpdate_1", "CronetCache", "configlist", "jscache", "jsengine", "surface", "biztest", "webcompt_debug", "mmslot", "tmpScanLicense", "webservice", "CDNTemp", "test_writable", "xlogtest_writable", "mars_mock"};

    /* renamed from: d */
    public static final String[] f349025d = {"${accountSd}/finder", "${accountSd}/sns", "${accountSd}/openapi_cache", "sns_ad_landingpages", "Cache", "${accountSd}/aimodel", "imgcache", "videocache", "${accountSd}/bizcache", "MixAudio", "${accountSd}/webcanvascache", "${accountSd}/brandicon", "${accountSd}/recordPlugin", "BigFile", "image", "${accountSd}/backupRecover", FirebaseAnalytics.C113378a.SHARE, "TMAssistantSDK", "ThumbVideoCache", "matrix_resource", "temp", "Diagnostic", "MicroMsg", "playable", "tt_tmpl_pkg", "wxacomplaint", "wxacache", "hprofs", "mars_mock", "ipxx_diag"};
}
