package gm3;

import com.tencent.matrix.batterycanary.monitor.feature.CpuStatFeature;
import com.tencent.p014mm.sdk.platformtools.MultiProcessMMKV;
import com.tencent.tav.coremedia.TimeUtil;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import java.util.Locale;
import java.util.TimeZone;
import p1195ge.C116947b;
import p933be.C79691a;
import p981ie.C87705i;

public final /* synthetic */ class b$$c implements C87705i {

    /* renamed from: a */
    public final /* synthetic */ StringBuilder f350539a;

    public /* synthetic */ b$$c(StringBuilder sb) {
        this.f350539a = sb;
    }

    public final void accept(Object obj) {
        StringBuilder sb = this.f350539a;
        C116947b.C116948a i = ((C116947b) obj).mo180931i();
        sb.append("\n");
        b$$d b__d = new b$$d();
        long j = MultiProcessMMKV.getDefault().getLong("batt_last_charged", 0);
        if (j > 0) {
            Calendar instance = Calendar.getInstance();
            instance.add(14, TimeZone.getDefault().getOffset(instance.getTimeInMillis()));
            SimpleDateFormat simpleDateFormat = new SimpleDateFormat(TimeUtil.YYYY2MM2DD_HH1MM1SS, Locale.getDefault());
            Date date = new Date(j);
            sb.append("[bat.chargeLast] ");
            sb.append(simpleDateFormat.format(date));
            sb.append("\n");
            sb.append("[bat.chargeLast] ");
            sb.append((String) b__d.apply(Long.valueOf(System.currentTimeMillis() - j)));
            sb.append(" ago\n");
        }
        C79691a.m96805b(CpuStatFeature.class, new b$$e(sb));
        sb.append("");
        sb.append("[power.cpu] ");
        sb.append(i.f350471g.f343211a);
        sb.append("\n");
        sb.append("[power.wakelocks] ");
        sb.append(i.f350473h.f343211a);
        sb.append("\n");
        sb.append("[power.mobile] ");
        sb.append(i.f350475i.f343211a);
        sb.append("\n");
        sb.append("[power.wifi] ");
        sb.append(i.f350477j.f343211a);
        sb.append("\n");
        sb.append("[power.blueTooth] ");
        sb.append(i.f350479k.f343211a);
        sb.append("\n");
        sb.append("[power.gps] ");
        sb.append(i.f350481l.f343211a);
        sb.append("\n");
        sb.append("[power.sensors] ");
        sb.append(i.f350483m.f343211a);
        sb.append("\n");
        sb.append("[power.camera] ");
        sb.append(i.f350485n.f343211a);
        sb.append("\n");
        sb.append("[power.flashLight] ");
        sb.append(i.f350487o.f343211a);
        sb.append("\n");
        sb.append("[power.audio] ");
        sb.append(i.f350489p.f343211a);
        sb.append("\n");
        sb.append("[power.video] ");
        sb.append(i.f350491q.f343211a);
        sb.append("\n");
        sb.append("[power.screen] ");
        sb.append(i.f350493r.f343211a);
        sb.append("\n");
        sb.append("[power.systemService] ");
        sb.append(i.f350495s.f343211a);
        sb.append("\n");
        sb.append("[power.idle] ");
        sb.append(i.f350497t.f343211a);
        sb.append("\n");
        sb.append("[power.total] ");
        sb.append(i.mo180934d());
        sb.append("\n");
        sb.append("");
        sb.append("\n");
        sb.append("[cpuPowerMams] ");
        sb.append(i.f350499u.f343211a);
        sb.append("\n");
        sb.append("[cpuUsrTimeMs] ");
        sb.append((String) b__d.apply((Long) i.f350501v.f343211a));
        sb.append("\n");
        sb.append("[cpuSysTimeMs] ");
        sb.append((String) b__d.apply((Long) i.f350503w.f343211a));
        sb.append("\n");
        sb.append("[realTimeMs] ");
        sb.append((String) b__d.apply((Long) i.f350505x.f343211a));
        sb.append("\n");
        sb.append("[upTimeMs] ");
        sb.append((String) b__d.apply((Long) i.f350507y.f343211a));
        sb.append("\n");
        sb.append("[offRealTimeMs] ");
        sb.append((String) b__d.apply((Long) i.f350509z.f343211a));
        sb.append("\n");
        sb.append("[offUpTimeMs] ");
        sb.append((String) b__d.apply((Long) i.f350436A.f343211a));
        sb.append("\n");
        sb.append("[mobilePowerMams] ");
        sb.append(i.f350437B.f343211a);
        sb.append("\n");
        sb.append("[mobileRadioActiveMs] ");
        sb.append((String) b__d.apply((Long) i.f350438C.f343211a));
        sb.append("\n");
        sb.append("[mobileIdleMs] ");
        sb.append((String) b__d.apply((Long) i.f350439D.f343211a));
        sb.append("\n");
        sb.append("[mobileRxMs] ");
        sb.append((String) b__d.apply((Long) i.f350440E.f343211a));
        sb.append("\n");
        sb.append("[mobileTxMs] ");
        sb.append((String) b__d.apply((Long) i.f350441F.f343211a));
        sb.append("\n");
        sb.append("[mobileRxBytes] ");
        sb.append(Long.valueOf(((Long) i.f350442G.f343211a).longValue() / TimeUtil.SECOND_TO_US));
        sb.append("\n");
        sb.append("[mobileTxBytes] ");
        sb.append(Long.valueOf(((Long) i.f350443H.f343211a).longValue() / TimeUtil.SECOND_TO_US));
        sb.append("\n");
        sb.append("[mobileRxPackets] ");
        sb.append(i.f350444I.f343211a);
        sb.append("\n");
        sb.append("[mobileTxPackets] ");
        sb.append(i.f350445J.f343211a);
        sb.append("\n");
        sb.append("[wifiPowerMams] ");
        sb.append(i.f350446K.f343211a);
        sb.append("\n");
        sb.append("[wifiIdleMs] ");
        sb.append((String) b__d.apply((Long) i.f350447L.f343211a));
        sb.append("\n");
        sb.append("[wifiRxMs] ");
        sb.append((String) b__d.apply((Long) i.f350448M.f343211a));
        sb.append("\n");
        sb.append("[wifiTxMs] ");
        sb.append((String) b__d.apply((Long) i.f350449N.f343211a));
        sb.append("\n");
        sb.append("[wifiRunningMs] ");
        sb.append((String) b__d.apply((Long) i.f350450O.f343211a));
        sb.append("\n");
        sb.append("[wifiLockMs] ");
        sb.append((String) b__d.apply((Long) i.f350451P.f343211a));
        sb.append("\n");
        sb.append("[wifiScanMs] ");
        sb.append((String) b__d.apply((Long) i.f350452Q.f343211a));
        sb.append("\n");
        sb.append("[wifiMulticastMs] ");
        sb.append((String) b__d.apply((Long) i.f350453R.f343211a));
        sb.append("\n");
        sb.append("[wifiRxBytes] ");
        sb.append(Long.valueOf(((Long) i.f350454S.f343211a).longValue() / TimeUtil.SECOND_TO_US));
        sb.append("\n");
        sb.append("[wifiTxBytes] ");
        sb.append(Long.valueOf(((Long) i.f350455T.f343211a).longValue() / TimeUtil.SECOND_TO_US));
        sb.append("\n");
        sb.append("[wifiRxPackets] ");
        sb.append(i.f350456U.f343211a);
        sb.append("\n");
        sb.append("[wifiTxPackets] ");
        sb.append(i.f350457V.f343211a);
        sb.append("\n");
        sb.append("[blueToothPowerMams] ");
        sb.append(i.f350458W.f343211a);
        sb.append("\n");
        sb.append("[blueToothIdleMs] ");
        sb.append((String) b__d.apply((Long) i.f350459X.f343211a));
        sb.append("\n");
        sb.append("[blueToothRxMs] ");
        sb.append((String) b__d.apply((Long) i.f350460Y.f343211a));
        sb.append("\n");
        sb.append("[blueToothTxMs] ");
        sb.append((String) b__d.apply((Long) i.f350461Z.f343211a));
        sb.append("\n");
        sb.append("[wakelocksPartialMs] ");
        sb.append((String) b__d.apply((Long) i.f350462a0.f343211a));
        sb.append("\n");
        sb.append("[wakelocksFullMs] ");
        sb.append((String) b__d.apply((Long) i.f350463b0.f343211a));
        sb.append("\n");
        sb.append("[wakelocksWindowMs] ");
        sb.append((String) b__d.apply((Long) i.f350464c0.f343211a));
        sb.append("\n");
        sb.append("[wakelocksDrawMs] ");
        sb.append((String) b__d.apply((Long) i.f350466d0.f343211a));
        sb.append("\n");
        sb.append("[wakelocksPidSum] ");
        sb.append((String) b__d.apply((Long) i.f350468e0.f343211a));
        sb.append("\n");
        sb.append("[gpsMs] ");
        sb.append((String) b__d.apply((Long) i.f350470f0.f343211a));
        sb.append("\n");
        sb.append("[sensorsPowerMams] ");
        sb.append(i.f350472g0.f343211a);
        sb.append("\n");
        sb.append("[cameraMs] ");
        sb.append((String) b__d.apply((Long) i.f350474h0.f343211a));
        sb.append("\n");
        sb.append("[flashLightMs] ");
        sb.append((String) b__d.apply((Long) i.f350476i0.f343211a));
        sb.append("\n");
        sb.append("[audioMs] ");
        sb.append((String) b__d.apply((Long) i.f350478j0.f343211a));
        sb.append("\n");
        sb.append("[videoMs] ");
        sb.append((String) b__d.apply((Long) i.f350480k0.f343211a));
        sb.append("\n");
        sb.append("[jobsMs] ");
        sb.append((String) b__d.apply((Long) i.f350482l0.f343211a));
        sb.append("\n");
        sb.append("[syncMs] ");
        sb.append((String) b__d.apply((Long) i.f350484m0.f343211a));
        sb.append("\n");
        sb.append("[fgActMs] ");
        sb.append((String) b__d.apply((Long) i.f350486n0.f343211a));
        sb.append("\n");
        sb.append("[procTopAppMs] ");
        sb.append((String) b__d.apply((Long) i.f350488o0.f343211a));
        sb.append("\n");
        sb.append("[procTopSleepMs] ");
        sb.append((String) b__d.apply((Long) i.f350490p0.f343211a));
        sb.append("\n");
        sb.append("[procFgMs] ");
        sb.append((String) b__d.apply((Long) i.f350492q0.f343211a));
        sb.append("\n");
        sb.append("[procFgSrvMs] ");
        sb.append((String) b__d.apply((Long) i.f350494r0.f343211a));
        sb.append("\n");
        sb.append("[procBgMs] ");
        sb.append((String) b__d.apply((Long) i.f350496s0.f343211a));
        sb.append("\n");
        sb.append("[procCacheMs] ");
        sb.append((String) b__d.apply((Long) i.f350498t0.f343211a));
        sb.append("\n");
        sb.append("");
    }
}
