package ak1;

/* renamed from: ak1.j0 */
public enum C0076j0 {
    CLICK_GIFT_BOARD_ENTRY_START_GIFT_BOARD(1),
    CLICK_GIFT_BOARD_INNER_GITF(2),
    SINGLE_OR_CONTINUE_CLICK_SELECT_GITF_SEND(3),
    CLICK_GIFT_BOARD_RIGHT_GREEN_ENTER_RECHARGE_UI(4),
    SEND_GIFT_MONEY_NOT_ENOUGH_DIALOG_EXPLORE(5),
    SEND_GIFT_MONEY_NOT_ENOUGH_CLICK_EXCHARGE_UI(6),
    GIFT_ICON_EXPOSURE(7),
    CLICK_HOT_LIST_SEE_CUR_DOU_YOU(8),
    RETURN_GIFT_BOARD_FROM_EXCHARGE_UI(9),
    RETURN_LIVE_ROOM_FROM_GIFT_BOARD(10),
    GIFT_BOARD_TURN_PAGE(11),
    CLICK_VISITOR_IN_HOT_LIST(12),
    CLICK_Y_IN_HOT_LIST(13),
    EXPOSE_HALF_BOARD_HOT_LIST(15),
    CLICK_PROFILE_HOT_LIST(18);
    

    /* renamed from: d */
    public final int f477d;

    /* access modifiers changed from: public */
    C0076j0(int i) {
        this.f477d = i;
    }
}
