package ak1;

/* renamed from: ak1.g0 */
public enum C0073g0 {
    LIVE_ANCHOR_ACTION_BEGIN(1),
    LIVE_ANCHOR_ACTION_EXCHANGE_CAMERA(2),
    LIVE_ANCHOR_ACTION_MINIMIZE(3),
    LIVE_ANCHOR_ACTION_COMMENT(4),
    LIVE_ANCHOR_ACTION_BARRAGE(5),
    LIVE_ANCHOR_ACTION_SHARE(6),
    LIVE_ANCHOR_ACTION_AUDIENCE(7),
    LIVE_ANCHOR_ACTION_COMMERCE(8),
    LIVE_ANCHOR_ACTION_OUT(9),
    LIVE_ANCHOR_TOP_COMMENT(10),
    LIVE_ANCHOR_TICKLE(11),
    LIVE_ANCHOR_LOTTERY(12),
    CLICK_FAIRY_STICK(13),
    BEAUTY(14),
    FILTER(15),
    CLICK_MIRROR(16),
    LINKMIC_SWITCH(17),
    LINKMIC_OP(18),
    GIFT_SWITCH(19),
    SEE_GIFT_LIST(20),
    LIVE_AUDIO_MODE(23),
    ANCHOR_MUSIC(24),
    ALERT_INFO(26),
    ANCHOR_PAUSE_LIVE(27),
    ANCHOR_BATTLE(28),
    SCREEN_SHARE(29),
    LIVE_BEAUTY(30),
    LIVE_ANCHOR_ACTION_LIKE(31),
    OPEN_HANDOFF(32),
    COMMENT_OPTION(33),
    NET_SPEED_LOW(34),
    PROMOTE_BANNER(35),
    PROFILE_HALF_SCREEN(36),
    FANS_CLUB(37),
    GIFT_ALLOWANCE(40),
    ANCHOR_APPLAUD(38),
    LIVE_DESC(39),
    MAKEUP(42),
    MODIFY_PAY_GAME_TEAM(41),
    PROMOTE_ANCHOR(43),
    ANCHOR_COMMENT(45),
    GameLive_PLAY_GAME_SETTING(44),
    PRODUCT_RECORD_ACTION(46),
    PRODUCT_SET_RECOMMEND(47),
    HALF_SCREEN_FROM_COMMENT(48),
    HALF_SCREEN_FROM_LIST(49),
    LIVE_ANCHOR_FAST_COMMENT(53),
    LIVE_MIC_INTERCOM(54),
    LIVING_SING_SONG(55),
    AUDIO_BG_OPERATION(56),
    ANCHOR_PROMOTION_MINI_APP(57),
    ANCHOR_BULLET_MSG(58),
    ANCHOR_GAME_TOGETHER(59),
    LIVE_QRCODE(60),
    LIVE_COMMENT_HEIGHT_CHANGE(61),
    FRAME_SCALE(62),
    LIVING_MENU(63),
    LIVE_RED_DOT(65),
    LIVE_DANMAKU_OPERATION(66),
    ANCHOR_ELEMENT(68);
    

    /* renamed from: d */
    public final int f448d;

    /* access modifiers changed from: public */
    C0073g0(int i) {
        this.f448d = i;
    }
}
