package com.tencent.p014mm.plugin.webview.webcompt;

/* renamed from: com.tencent.mm.plugin.webview.webcompt.b */
public enum C44406b {
    PKG_SCRIPT_FROM_ASSESTS(40),
    PKG_SCRIPT_FROM_PACKAGE(41),
    APP_SCRIPT_FROM_CACHE(42),
    APP_SCRIPT_FROM_NETWORK(43),
    APP_SCRIPT_DOWNLOAD(46),
    APP_SCRIPT_DOWNLOAD_ERR(47),
    APP_SCRIPT_MD5_INVALID(48),
    EX_APP_SCRIPT(49),
    AUTH_WITH_APP_CHANGE(55),
    AUTH_WITH_FIRST_TIME(56),
    REAUTH(57),
    EVAL_MAIN_FRAME(60),
    CREATE_JS_CONTEXT(62),
    CREATE_JS_CONTEXT_ERR(63),
    PRELOAD_JS_CONTEXT(66),
    PRELOAD_JS_CONTEXT_USE(67),
    GET_A8KEY(70),
    GET_A8KEY_SUCC(71),
    GET_A8KEY_ERR(72),
    LOAD_APP_SCRIPT(73),
    LOAD_APP_SCRIPT_SUCC(74),
    LOAD_APP_SCRIPT_ERR(75),
    EX_JS_CONTEXT(80),
    IFRAME_INTERCEPT(81),
    IFRAME_INTERCEPT_SUCC(83),
    IFRAME_INTERCEPT_ERR(84),
    SEND_TO_JS_CONTEXT(85),
    SEND_TO_MAIN_FRAME(86),
    REQUEST_CGI(87),
    REQUEST_CGI_ERR(88),
    REQUEST_JS_ERR_REPORT(90),
    REQUEST_JS_ERR_REPORT_ERR(91),
    SEND_EVENT_TO_JS_CONTEXT(92),
    PARSE_RES_VERSION_ERR(93),
    RECYCLE_JS_CXT(100),
    RECYCLE_JS_CXT_USE(101);
    

    /* renamed from: d */
    public final int f120393d;

    /* access modifiers changed from: public */
    C44406b(int i) {
        this.f120393d = i;
    }
}
