package com.tencent.p014mm.plugin.appbrand.step;

import com.tencent.p014mm.sdk.platformtools.WeChatBrands;
import java.util.ArrayList;
import java.util.List;
import uo0.C78248f;
import uo0.C90709a;
import uo0.C90713g;
import uo0.C90714h;
import uo0.C90715k;

/* renamed from: com.tencent.mm.plugin.appbrand.step.KSProcessWeAppLaunch */
public final class KSProcessWeAppLaunch {
    public static final String NAME = "WeAppLaunch";
    public static final List<C78248f> sStepNodes;
    public static C90709a stepCheckBan;
    public static C90709a stepColdLaunchFailed;
    public static C90709a stepContainerUILaunch;
    public static C90709a stepCreateMagicBrushView;
    public static C90709a stepCreatePageUI;
    public static C90709a stepCreatePageUI_Game;
    public static C90709a stepCreateWebViewInstance;
    public static C90709a stepGenerateFuncReadyRespond;
    public static C90709a stepGetContact;
    public static C90709a stepGetContact_CGI;
    public static C90709a stepGetContact_DB;
    public static C90709a stepInitRuntimeGroup;
    public static C90709a stepInitRuntimeGroup_Game;
    public static C90709a stepInjectJSAppService;
    public static C90709a stepInjectJSGame;
    public static C90709a stepInjectJSPageScript;
    public static C90709a stepInjectJSWAMainContext;
    public static C90709a stepInjectJSWASubContext;
    public static C90709a stepInjectJSWAWebview;
    public static C90709a stepInjectWAGameContext;
    public static C90709a stepInjectWAGameSubContext;
    public static C90709a stepInjectWAPageFrameHtml;
    public static C90709a stepInjectWxConfig;
    public static C90709a stepInjectWxConfig_Game;
    public static C90709a stepInstallLibraries;
    public static C90709a stepLaunch;
    public static C90709a stepPageInit;
    public static C90709a stepPageInitUIGroup;
    public static C90709a stepPageInitUIGroup_Game;
    public static C90709a stepPageInit_Game;
    public static C90709a stepPageReady;
    public static C90709a stepPageReady_Game;
    public static C90709a stepPrepareMainProcess;
    public static C90709a stepPrepareResourceGroup;
    public static C90709a stepPrepareResourceProcess;
    public static C90709a stepPrepareResourceSubProcessCodePkg_DB;
    public static C90709a stepPrepareResourceSubProcessCodePkg_Download;
    public static C90709a stepPrepareResourceSubProcessLaunchWxaApp_CGI;
    public static C90709a stepPrepareResourceSubProcessLaunchWxaApp_DB;
    public static C90709a stepPrepareResourceTimeout;
    public static C90709a stepPrepareResourceWaitForResult;
    public static C90709a stepPrepareRuntime;
    public static C90709a stepPrepareWebView;
    public static C90709a stepServiceInit;
    public static C90709a stepServiceInit_Game;
    public static C90709a stepSetupConfigsPostResourcePrepared;
    public static C90709a stepSurfaceAvailable;
    public static C90709a stepVdSync;
    public static C90709a stepWaitForAppServiceAheadPreloadDone;
    public static C90709a stepWaitForAppServicePreloadDone;
    public static C90709a stepWaitForCommLibConfirm;
    public static C90709a stepWaitForWebViewAheadPreloadDone;
    public static C90709a stepWaitForWebViewPreloadDone;

    static {
        ArrayList arrayList = new ArrayList();
        sStepNodes = arrayList;
        arrayList.add(new C90715k(NAME));
        C90713g gVar = new C90713g(NAME, "Launch", true, false, "", 2, 0, 12, "");
        stepLaunch = gVar;
        arrayList.add(gVar);
        C90713g gVar2 = new C90713g(NAME, "GetContact", true, false, "", 3, 12, 13, "");
        stepGetContact = gVar2;
        arrayList.add(gVar2);
        C90713g gVar3 = new C90713g(NAME, "GetContact_DB", true, true, "读取contact信息", 1, 13, Integer.MIN_VALUE, "");
        stepGetContact_DB = gVar3;
        arrayList.add(gVar3);
        C90713g gVar4 = new C90713g(NAME, "GetContact_CGI", false, true, "拉contact cgi", 1, 13, Integer.MIN_VALUE, "");
        stepGetContact_CGI = gVar4;
        arrayList.add(gVar4);
        C90713g gVar5 = new C90713g(NAME, "CheckBan", true, false, "封禁逻辑", 1, 12, Integer.MIN_VALUE, "");
        stepCheckBan = gVar5;
        arrayList.add(gVar5);
        C90713g gVar6 = new C90713g(NAME, "ContainerUILaunch", true, true, "拉起容器UI界面", 1, 12, Integer.MIN_VALUE, "");
        stepContainerUILaunch = gVar6;
        arrayList.add(gVar6);
        C90713g gVar7 = new C90713g(NAME, "PrepareRuntime", true, false, "", 3, 12, 14, "");
        stepPrepareRuntime = gVar7;
        arrayList.add(gVar7);
        C90713g gVar8 = new C90713g(NAME, "PrepareMainProcess", true, true, "准备主进程通讯", 1, 14, Integer.MIN_VALUE, "");
        stepPrepareMainProcess = gVar8;
        arrayList.add(gVar8);
        C90713g gVar9 = new C90713g(NAME, "InstallLibraries", true, true, "动态安装小程序环境所需二进制库", 1, 14, Integer.MIN_VALUE, "");
        stepInstallLibraries = gVar9;
        arrayList.add(gVar9);
        C90713g gVar10 = new C90713g(NAME, "PrepareWebView", true, true, "准备WebView (View)", 1, 14, Integer.MIN_VALUE, "");
        stepPrepareWebView = gVar10;
        arrayList.add(gVar10);
        C90713g gVar11 = new C90713g(NAME, "PrepareResourceGroup", true, false, "Launch CGI及准备小程序包", 3, 14, 15, "");
        stepPrepareResourceGroup = gVar11;
        arrayList.add(gVar11);
        C90713g gVar12 = new C90713g(NAME, "PrepareResourceProcess", true, false, "资源准备逻辑过程", 1, 15, Integer.MIN_VALUE, "");
        stepPrepareResourceProcess = gVar12;
        arrayList.add(gVar12);
        C90713g gVar13 = new C90713g(NAME, "PrepareResourceWaitForResult", true, false, "runtime监听过程结果", 1, 15, Integer.MIN_VALUE, "");
        stepPrepareResourceWaitForResult = gVar13;
        arrayList.add(gVar13);
        C90713g gVar14 = new C90713g(NAME, "PrepareResourceTimeout", true, true, "资源准备10s超时事件", 1, 15, Integer.MIN_VALUE, "");
        stepPrepareResourceTimeout = gVar14;
        arrayList.add(gVar14);
        C90713g gVar15 = new C90713g(NAME, "PrepareResourceSubProcessLaunchWxaApp_DB", true, true, "使用本地缓存的launch数据打开", 1, 15, Integer.MIN_VALUE, "");
        stepPrepareResourceSubProcessLaunchWxaApp_DB = gVar15;
        arrayList.add(gVar15);
        C90713g gVar16 = new C90713g(NAME, "PrepareResourceSubProcessLaunchWxaApp_CGI", true, true, "同步请求launch数据打开", 1, 15, Integer.MIN_VALUE, "");
        stepPrepareResourceSubProcessLaunchWxaApp_CGI = gVar16;
        arrayList.add(gVar16);
        C90713g gVar17 = new C90713g(NAME, "PrepareResourceSubProcessCodePkg_DB", true, true, "使用本地缓存好的代码包打开", 1, 15, Integer.MIN_VALUE, "");
        stepPrepareResourceSubProcessCodePkg_DB = gVar17;
        arrayList.add(gVar17);
        C90713g gVar18 = new C90713g(NAME, "PrepareResourceSubProcessCodePkg_Download", true, true, "同步下载代码包打开", 1, 15, Integer.MIN_VALUE, "");
        stepPrepareResourceSubProcessCodePkg_Download = gVar18;
        arrayList.add(gVar18);
        C90713g gVar19 = new C90713g(NAME, "SetupConfigsPostResourcePrepared", true, false, "资源准备完的配置解析", 1, 14, Integer.MIN_VALUE, "");
        stepSetupConfigsPostResourcePrepared = gVar19;
        arrayList.add(gVar19);
        C90713g gVar20 = new C90713g(NAME, "WaitForCommLibConfirm", true, true, "确定基础库版本", 1, 14, Integer.MIN_VALUE, "");
        stepWaitForCommLibConfirm = gVar20;
        arrayList.add(gVar20);
        C90713g gVar21 = new C90713g(NAME, "WaitForWebViewPreloadDone", true, true, "等待启动前预加载webview完成 (View)", 1, 14, Integer.MIN_VALUE, "");
        stepWaitForWebViewPreloadDone = gVar21;
        arrayList.add(gVar21);
        C90713g gVar22 = new C90713g(NAME, "WaitForWebViewAheadPreloadDone", true, true, "等待运行时预加载webview完成 (View)", 1, 14, Integer.MIN_VALUE, "");
        stepWaitForWebViewAheadPreloadDone = gVar22;
        arrayList.add(gVar22);
        C90713g gVar23 = new C90713g(NAME, "WaitForAppServicePreloadDone", true, true, "等待启动前预加载appservice完成 (Service)", 1, 14, Integer.MIN_VALUE, "");
        stepWaitForAppServicePreloadDone = gVar23;
        arrayList.add(gVar23);
        C90713g gVar24 = new C90713g(NAME, "WaitForAppServiceAheadPreloadDone", true, true, "等待运行时预加载appservice完成 (Service)", 1, 14, Integer.MIN_VALUE, "");
        stepWaitForAppServiceAheadPreloadDone = gVar24;
        arrayList.add(gVar24);
        C90713g gVar25 = new C90713g(NAME, "InitRuntimeGroup", true, false, "", 3, 12, 16, WeChatBrands.Business.GROUP_MP);
        stepInitRuntimeGroup = gVar25;
        arrayList.add(gVar25);
        C90713g gVar26 = new C90713g(NAME, "ServiceInit", true, false, "", 2, 16, 17, "");
        stepServiceInit = gVar26;
        arrayList.add(gVar26);
        C90713g gVar27 = new C90713g(NAME, "InjectJSWAMainContext", true, true, "注入WAMainContext.js (Service)", 1, 17, Integer.MIN_VALUE, "");
        stepInjectJSWAMainContext = gVar27;
        arrayList.add(gVar27);
        C90713g gVar28 = new C90713g(NAME, "InjectJSWASubContext", true, true, "注入WASubContext.js (Service)", 1, 17, Integer.MIN_VALUE, "");
        stepInjectJSWASubContext = gVar28;
        arrayList.add(gVar28);
        C90713g gVar29 = new C90713g(NAME, "InjectJSAppService", true, true, "注入appservice.js (Service)", 1, 17, Integer.MIN_VALUE, "");
        stepInjectJSAppService = gVar29;
        arrayList.add(gVar29);
        C90713g gVar30 = new C90713g(NAME, "InjectWxConfig", true, true, "注入wxConfig (Service)", 1, 17, Integer.MIN_VALUE, "");
        stepInjectWxConfig = gVar30;
        arrayList.add(gVar30);
        C90713g gVar31 = new C90713g(NAME, "PageInit", true, false, "", 2, 16, 18, "");
        stepPageInit = gVar31;
        arrayList.add(gVar31);
        C90713g gVar32 = new C90713g(NAME, "PageInitUIGroup", true, false, "", 3, 18, 19, "");
        stepPageInitUIGroup = gVar32;
        arrayList.add(gVar32);
        C90713g gVar33 = new C90713g(NAME, "CreatePageUI", true, false, "首页界面创建", 1, 19, Integer.MIN_VALUE, "");
        stepCreatePageUI = gVar33;
        arrayList.add(gVar33);
        C90713g gVar34 = new C90713g(NAME, "CreateWebViewInstance", true, true, "", 1, 19, Integer.MIN_VALUE, "");
        stepCreateWebViewInstance = gVar34;
        arrayList.add(gVar34);
        C90713g gVar35 = new C90713g(NAME, "InjectWAPageFrameHtml", true, true, "注入WAPageframe.html (View)", 1, 18, Integer.MIN_VALUE, "");
        stepInjectWAPageFrameHtml = gVar35;
        arrayList.add(gVar35);
        C90713g gVar36 = new C90713g(NAME, "InjectJSWAWebview", true, true, "注入WAWebview.js (View)", 1, 18, Integer.MIN_VALUE, "");
        stepInjectJSWAWebview = gVar36;
        arrayList.add(gVar36);
        C90713g gVar37 = new C90713g(NAME, "InjectJSPageScript", true, false, "页面js注入 (View)", 1, 18, Integer.MIN_VALUE, "");
        stepInjectJSPageScript = gVar37;
        arrayList.add(gVar37);
        C90713g gVar38 = new C90713g(NAME, "GenerateFuncReadyRespond", false, false, "webview发出的GenerateFuncReady被appservice响应 (View)", 1, 18, Integer.MIN_VALUE, "");
        stepGenerateFuncReadyRespond = gVar38;
        arrayList.add(gVar38);
        C90713g gVar39 = new C90713g(NAME, "VdSync", true, false, "第一次VdSync (View) ", 1, 18, Integer.MIN_VALUE, "");
        stepVdSync = gVar39;
        arrayList.add(gVar39);
        C90713g gVar40 = new C90713g(NAME, "PageReady", true, false, "page ready (View)", 1, 18, Integer.MIN_VALUE, "");
        stepPageReady = gVar40;
        arrayList.add(gVar40);
        C90713g gVar41 = new C90713g(NAME, "InitRuntimeGroup_Game", true, false, "", 3, 12, 20, "game");
        stepInitRuntimeGroup_Game = gVar41;
        arrayList.add(gVar41);
        C90713g gVar42 = new C90713g(NAME, "ServiceInit_Game", true, false, "", 2, 20, 21, "");
        stepServiceInit_Game = gVar42;
        arrayList.add(gVar42);
        C90713g gVar43 = new C90713g(NAME, "InjectWAGameContext", true, true, "注入 WAGame.js (Service)", 1, 21, Integer.MIN_VALUE, "");
        stepInjectWAGameContext = gVar43;
        arrayList.add(gVar43);
        C90713g gVar44 = new C90713g(NAME, "InjectWAGameSubContext", true, true, "注入 WAGameSubContext.js (Service) ", 1, 21, Integer.MIN_VALUE, "");
        stepInjectWAGameSubContext = gVar44;
        arrayList.add(gVar44);
        C90713g gVar45 = new C90713g(NAME, "InjectJSGame", true, true, "注入game.js (Service)", 1, 21, Integer.MIN_VALUE, "");
        stepInjectJSGame = gVar45;
        arrayList.add(gVar45);
        C90713g gVar46 = new C90713g(NAME, "InjectWxConfig_Game", true, true, "注入wxConfig (Service)", 1, 21, Integer.MIN_VALUE, "");
        stepInjectWxConfig_Game = gVar46;
        arrayList.add(gVar46);
        C90713g gVar47 = new C90713g(NAME, "PageInit_Game", true, false, "", 2, 20, 22, "");
        stepPageInit_Game = gVar47;
        arrayList.add(gVar47);
        C90713g gVar48 = new C90713g(NAME, "PageInitUIGroup_Game", true, false, "", 3, 22, 23, "");
        stepPageInitUIGroup_Game = gVar48;
        arrayList.add(gVar48);
        C90713g gVar49 = new C90713g(NAME, "CreatePageUI_Game", true, false, "首页界面创建", 1, 23, Integer.MIN_VALUE, "");
        stepCreatePageUI_Game = gVar49;
        arrayList.add(gVar49);
        C90713g gVar50 = new C90713g(NAME, "CreateMagicBrushView", true, true, "", 1, 23, Integer.MIN_VALUE, "");
        stepCreateMagicBrushView = gVar50;
        arrayList.add(gVar50);
        C90713g gVar51 = new C90713g(NAME, "SurfaceAvailable", true, false, "SurfaceAvailable (View)", 1, 22, Integer.MIN_VALUE, "");
        stepSurfaceAvailable = gVar51;
        arrayList.add(gVar51);
        C90713g gVar52 = new C90713g(NAME, "PageReady_Game", true, false, "page ready (View)", 1, 22, Integer.MIN_VALUE, "");
        stepPageReady_Game = gVar52;
        arrayList.add(gVar52);
        C90713g gVar53 = new C90713g(NAME, "ColdLaunchFailed", true, true, "", 1, 12, Integer.MIN_VALUE, "");
        stepColdLaunchFailed = gVar53;
        arrayList.add(gVar53);
        arrayList.add(new C90714h(NAME));
    }
}
