package x91;

/* renamed from: x91.e */
public enum C23072e {
    MATCH_PAGE_RESUME,
    MATCH_PAGE_FINISH,
    MATCH_PAGE_SLIENCE_POP_STACK,
    MATCH_PAGE_8_EVENT,
    MATCH_PAGE_MM_PROCESS_RESTEART,
    MATCH_PAGE_SESSION_CLOSE
}
