package com.tencent.p014mm.autogen.mmdata.rpt;

import com.tencent.midas.comm.log.util.APLogFileUtil;
import com.tencent.xweb.file.XVFSFile;
import kj2.C61103a;

/* renamed from: com.tencent.mm.autogen.mmdata.rpt.Struct12076 */
public final class Struct12076 extends C61103a {
    public Struct12076() {
        mo86052l("BrowseTime", 0);
        mo86052l("BrowseFeedCount", 0);
        mo86052l("CommentOrLikeFeedCount", 0);
        mo86052l("ClickFeedCount", 0);
        mo86052l("ClickAlbumCount", 0);
        mo86052l("PostFeedCount", 0);
        mo86052l("ExposeFeedCount", 0);
        mo86052l("FavFeedCount", 0);
        mo86052l("BlackListFriendCount", 0);
        mo86052l("OutsiderFriendCount", 0);
        mo86052l("BrowseNewFeedCount", 0);
        mo86052l("HasNewSnsMsgWhenEntrance", 0);
        mo86052l("HasNewChatMsgWhenExit", 0);
        mo86052l("StartBrowseSnsObjectId", "");
        mo86052l("EndBrowseSnsObjectId", "");
        mo86052l("NextBrowseSnsObjectId", "");
        mo86052l("HasNewFeedInServer", 0);
        mo86052l("BrowseBrandUrlFeedCount", 0);
        mo86052l("BrowseNotBrandUrlFeedCount", 0);
        mo86052l("BrowseTextFeedCount", 0);
        mo86052l("BrowseImageFeedCount", 0);
        mo86052l("BrowseSightFeedCount", 0);
        mo86052l("BrowseAdFeedCount", 0);
        mo86052l("BrowseMusicFeedCount", 0);
        mo86052l("contactCount", 0);
        mo86052l("BrowseVideoFeedCount", 0);
        mo86052l("ClickBrandUrlFeedCount", 0);
        mo86052l("ClickNotBrandUrlFeedCount", 0);
        mo86052l("ClickImageFeedCount", 0);
        mo86052l("ClickSightFeedCount", 0);
        mo86052l("ClickMusicFeedCount", 0);
        mo86052l("ClickVideoFeedCount", 0);
        mo86052l("BrowseOtherFeedCount", 0);
        mo86052l("BrowserStreamVideoFeedCount", 0);
        mo86052l("ClickStreamVideoCount", 0);
        mo86052l("ClickAdFeed", 0);
        mo86052l("BackGroundTime", 0);
        mo86052l("BrowseTimeLineTime", 0);
        mo86052l("BrowseMyAlbumTime", 0);
        mo86052l("BrowseOtherAlbumTime", 0);
        mo86052l("BrowseMessageListTime", 0);
        mo86052l("ClickNewPostTime", 0);
        mo86052l("BrowseFullScreenImageTime", 0);
        mo86052l("BrowseFullScreenSightTime", 0);
        mo86052l("BrowseMPArticleTime", 0);
        mo86052l("BrowseExternalArticleTime", 0);
        mo86052l("BrowseAdFullScreenTime", 0);
        mo86052l("BrowseAdSightTime", 0);
        mo86052l("BrowseAdDetailTime", 0);
        mo86052l("BrowseAdShortVideoTime", 0);
        mo86052l("BrowseAdLongVideoTime", 0);
        mo86052l("BrowseForwardAdLongVideoTime", 0);
        mo86052l("StartBrowseTime", 0);
        mo86052l("ClickFeedIdList", "");
        mo86052l("ExposeFeedIdList", "");
        mo86052l("FavFeedIdList", "");
        mo86052l("ClickAlbumUserList", "");
        mo86052l("ForwardFeedIdList", "");
        mo86052l("ClickAvatarFeedIdList", "");
        mo86052l("ClickNickNameFeedIdList", "");
        mo86052l("ForwardToSingleChatFeedIdList", "");
        mo86052l("ForwardToChatRoomFeedIdList", "");
        mo86052l("FeedUpdateNotification", 0);
        mo86052l("UnReadLikeCount", 0);
        mo86052l("UnReadCommentCount", 0);
        mo86052l("LastestUnReadFeedId", "");
        mo86052l("UnReadMsgCount", 0);
        mo86052l("BrowseAdCanvasPageTime", 0);
        mo86052l("BrowseForwardAdCanvasTime", 0);
        mo86052l("RedDotSource", 0);
        mo86052l("EnterObjectId", "");
        mo86052l("like_feed_count", 0);
        mo86052l("comment_feed_count", 0);
        mo86052l("next_page_count", 0);
        mo86052l("BrowseMuiscPlayerFeedCount", 0);
        mo86052l("ClickMuiscPlayerFeedCount", 0);
        mo86052l("MusicPlayerFeedTime", 0);
        mo86052l("BrowseClickFinderFeedCnt", 0);
        mo86052l("FinderFeedTime", 0);
        mo86052l("ClickFinderFeedCnt", 0);
    }

    /* renamed from: j */
    public int mo1004j() {
        return 12076;
    }

    /* renamed from: p */
    public String mo1005p() {
        StringBuffer stringBuffer = new StringBuffer();
        stringBuffer.append(mo86050i("BrowseTime"));
        stringBuffer.append(",");
        stringBuffer.append(mo86050i("BrowseFeedCount"));
        stringBuffer.append(",");
        stringBuffer.append(mo86050i("CommentOrLikeFeedCount"));
        stringBuffer.append(",");
        stringBuffer.append(mo86050i("ClickFeedCount"));
        stringBuffer.append(",");
        stringBuffer.append(mo86050i("ClickAlbumCount"));
        stringBuffer.append(",");
        stringBuffer.append(mo86050i("PostFeedCount"));
        stringBuffer.append(",");
        stringBuffer.append(mo86050i("ExposeFeedCount"));
        stringBuffer.append(",");
        stringBuffer.append(mo86050i("FavFeedCount"));
        stringBuffer.append(",");
        stringBuffer.append(mo86050i("BlackListFriendCount"));
        stringBuffer.append(",");
        stringBuffer.append(mo86050i("OutsiderFriendCount"));
        stringBuffer.append(",");
        stringBuffer.append(mo86050i("BrowseNewFeedCount"));
        stringBuffer.append(",");
        stringBuffer.append(mo86050i("HasNewSnsMsgWhenEntrance"));
        stringBuffer.append(",");
        stringBuffer.append(mo86050i("HasNewChatMsgWhenExit"));
        stringBuffer.append(",");
        stringBuffer.append(mo86050i("StartBrowseSnsObjectId"));
        stringBuffer.append(",");
        stringBuffer.append(mo86050i("EndBrowseSnsObjectId"));
        stringBuffer.append(",");
        stringBuffer.append(mo86050i("NextBrowseSnsObjectId"));
        stringBuffer.append(",");
        stringBuffer.append(mo86050i("HasNewFeedInServer"));
        stringBuffer.append(",");
        stringBuffer.append(mo86050i("BrowseBrandUrlFeedCount"));
        stringBuffer.append(",");
        stringBuffer.append(mo86050i("BrowseNotBrandUrlFeedCount"));
        stringBuffer.append(",");
        stringBuffer.append(mo86050i("BrowseTextFeedCount"));
        stringBuffer.append(",");
        stringBuffer.append(mo86050i("BrowseImageFeedCount"));
        stringBuffer.append(",");
        stringBuffer.append(mo86050i("BrowseSightFeedCount"));
        stringBuffer.append(",");
        stringBuffer.append(mo86050i("BrowseAdFeedCount"));
        stringBuffer.append(",");
        stringBuffer.append(mo86050i("BrowseMusicFeedCount"));
        stringBuffer.append(",");
        stringBuffer.append(mo86050i("contactCount"));
        stringBuffer.append(",");
        stringBuffer.append(mo86050i("BrowseVideoFeedCount"));
        stringBuffer.append(",");
        stringBuffer.append(mo86050i("ClickBrandUrlFeedCount"));
        stringBuffer.append(",");
        stringBuffer.append(mo86050i("ClickNotBrandUrlFeedCount"));
        stringBuffer.append(",");
        stringBuffer.append(mo86050i("ClickImageFeedCount"));
        stringBuffer.append(",");
        stringBuffer.append(mo86050i("ClickSightFeedCount"));
        stringBuffer.append(",");
        stringBuffer.append(mo86050i("ClickMusicFeedCount"));
        stringBuffer.append(",");
        stringBuffer.append(mo86050i("ClickVideoFeedCount"));
        stringBuffer.append(",");
        stringBuffer.append(mo86050i("BrowseOtherFeedCount"));
        stringBuffer.append(",");
        stringBuffer.append(mo86050i("BrowserStreamVideoFeedCount"));
        stringBuffer.append(",");
        stringBuffer.append(mo86050i("ClickStreamVideoCount"));
        stringBuffer.append(",");
        stringBuffer.append(mo86050i("ClickAdFeed"));
        stringBuffer.append(",");
        stringBuffer.append(mo86050i("BackGroundTime"));
        stringBuffer.append(",");
        stringBuffer.append(mo86050i("BrowseTimeLineTime"));
        stringBuffer.append(",");
        stringBuffer.append(mo86050i("BrowseMyAlbumTime"));
        stringBuffer.append(",");
        stringBuffer.append(mo86050i("BrowseOtherAlbumTime"));
        stringBuffer.append(",");
        stringBuffer.append(mo86050i("BrowseMessageListTime"));
        stringBuffer.append(",");
        stringBuffer.append(mo86050i("ClickNewPostTime"));
        stringBuffer.append(",");
        stringBuffer.append(mo86050i("BrowseFullScreenImageTime"));
        stringBuffer.append(",");
        stringBuffer.append(mo86050i("BrowseFullScreenSightTime"));
        stringBuffer.append(",");
        stringBuffer.append(mo86050i("BrowseMPArticleTime"));
        stringBuffer.append(",");
        stringBuffer.append(mo86050i("BrowseExternalArticleTime"));
        stringBuffer.append(",");
        stringBuffer.append(mo86050i("BrowseAdFullScreenTime"));
        stringBuffer.append(",");
        stringBuffer.append(mo86050i("BrowseAdSightTime"));
        stringBuffer.append(",");
        stringBuffer.append(mo86050i("BrowseAdDetailTime"));
        stringBuffer.append(",");
        stringBuffer.append(mo86050i("BrowseAdShortVideoTime"));
        stringBuffer.append(",");
        stringBuffer.append(mo86050i("BrowseAdLongVideoTime"));
        stringBuffer.append(",");
        stringBuffer.append(mo86050i("BrowseForwardAdLongVideoTime"));
        stringBuffer.append(",");
        stringBuffer.append(mo86050i("StartBrowseTime"));
        stringBuffer.append(",");
        stringBuffer.append(mo86050i("ClickFeedIdList"));
        stringBuffer.append(",");
        stringBuffer.append(mo86050i("ExposeFeedIdList"));
        stringBuffer.append(",");
        stringBuffer.append(mo86050i("FavFeedIdList"));
        stringBuffer.append(",");
        stringBuffer.append(mo86050i("ClickAlbumUserList"));
        stringBuffer.append(",");
        stringBuffer.append(mo86050i("ForwardFeedIdList"));
        stringBuffer.append(",");
        stringBuffer.append(mo86050i("ClickAvatarFeedIdList"));
        stringBuffer.append(",");
        stringBuffer.append(mo86050i("ClickNickNameFeedIdList"));
        stringBuffer.append(",");
        stringBuffer.append(mo86050i("ForwardToSingleChatFeedIdList"));
        stringBuffer.append(",");
        stringBuffer.append(mo86050i("ForwardToChatRoomFeedIdList"));
        stringBuffer.append(",");
        stringBuffer.append(mo86050i("FeedUpdateNotification"));
        stringBuffer.append(",");
        stringBuffer.append(mo86050i("UnReadLikeCount"));
        stringBuffer.append(",");
        stringBuffer.append(mo86050i("UnReadCommentCount"));
        stringBuffer.append(",");
        stringBuffer.append(mo86050i("LastestUnReadFeedId"));
        stringBuffer.append(",");
        stringBuffer.append(mo86050i("UnReadMsgCount"));
        stringBuffer.append(",");
        stringBuffer.append(mo86050i("BrowseAdCanvasPageTime"));
        stringBuffer.append(",");
        stringBuffer.append(mo86050i("BrowseForwardAdCanvasTime"));
        stringBuffer.append(",");
        stringBuffer.append(mo86050i("RedDotSource"));
        stringBuffer.append(",");
        stringBuffer.append(mo86050i("EnterObjectId"));
        stringBuffer.append(",");
        stringBuffer.append(mo86050i("like_feed_count"));
        stringBuffer.append(",");
        stringBuffer.append(mo86050i("comment_feed_count"));
        stringBuffer.append(",");
        stringBuffer.append(mo86050i("next_page_count"));
        stringBuffer.append(",");
        stringBuffer.append(mo86050i("BrowseMuiscPlayerFeedCount"));
        stringBuffer.append(",");
        stringBuffer.append(mo86050i("ClickMuiscPlayerFeedCount"));
        stringBuffer.append(",");
        stringBuffer.append(mo86050i("MusicPlayerFeedTime"));
        stringBuffer.append(",");
        stringBuffer.append(mo86050i("BrowseClickFinderFeedCnt"));
        stringBuffer.append(",");
        stringBuffer.append(mo86050i("FinderFeedTime"));
        stringBuffer.append(",");
        stringBuffer.append(mo86050i("ClickFinderFeedCnt"));
        String stringBuffer2 = stringBuffer.toString();
        mo86044a(stringBuffer2);
        return stringBuffer2;
    }

    /* renamed from: q */
    public String mo1006q() {
        StringBuffer stringBuffer = new StringBuffer();
        stringBuffer.append("BrowseTime");
        stringBuffer.append(XVFSFile.PATH_SEPARATOR);
        stringBuffer.append(mo86050i("BrowseTime"));
        stringBuffer.append(APLogFileUtil.SEPARATOR_LINE);
        stringBuffer.append("BrowseFeedCount");
        stringBuffer.append(XVFSFile.PATH_SEPARATOR);
        stringBuffer.append(mo86050i("BrowseFeedCount"));
        stringBuffer.append(APLogFileUtil.SEPARATOR_LINE);
        stringBuffer.append("CommentOrLikeFeedCount");
        stringBuffer.append(XVFSFile.PATH_SEPARATOR);
        stringBuffer.append(mo86050i("CommentOrLikeFeedCount"));
        stringBuffer.append(APLogFileUtil.SEPARATOR_LINE);
        stringBuffer.append("ClickFeedCount");
        stringBuffer.append(XVFSFile.PATH_SEPARATOR);
        stringBuffer.append(mo86050i("ClickFeedCount"));
        stringBuffer.append(APLogFileUtil.SEPARATOR_LINE);
        stringBuffer.append("ClickAlbumCount");
        stringBuffer.append(XVFSFile.PATH_SEPARATOR);
        stringBuffer.append(mo86050i("ClickAlbumCount"));
        stringBuffer.append(APLogFileUtil.SEPARATOR_LINE);
        stringBuffer.append("PostFeedCount");
        stringBuffer.append(XVFSFile.PATH_SEPARATOR);
        stringBuffer.append(mo86050i("PostFeedCount"));
        stringBuffer.append(APLogFileUtil.SEPARATOR_LINE);
        stringBuffer.append("ExposeFeedCount");
        stringBuffer.append(XVFSFile.PATH_SEPARATOR);
        stringBuffer.append(mo86050i("ExposeFeedCount"));
        stringBuffer.append(APLogFileUtil.SEPARATOR_LINE);
        stringBuffer.append("FavFeedCount");
        stringBuffer.append(XVFSFile.PATH_SEPARATOR);
        stringBuffer.append(mo86050i("FavFeedCount"));
        stringBuffer.append(APLogFileUtil.SEPARATOR_LINE);
        stringBuffer.append("BlackListFriendCount");
        stringBuffer.append(XVFSFile.PATH_SEPARATOR);
        stringBuffer.append(mo86050i("BlackListFriendCount"));
        stringBuffer.append(APLogFileUtil.SEPARATOR_LINE);
        stringBuffer.append("OutsiderFriendCount");
        stringBuffer.append(XVFSFile.PATH_SEPARATOR);
        stringBuffer.append(mo86050i("OutsiderFriendCount"));
        stringBuffer.append(APLogFileUtil.SEPARATOR_LINE);
        stringBuffer.append("BrowseNewFeedCount");
        stringBuffer.append(XVFSFile.PATH_SEPARATOR);
        stringBuffer.append(mo86050i("BrowseNewFeedCount"));
        stringBuffer.append(APLogFileUtil.SEPARATOR_LINE);
        stringBuffer.append("HasNewSnsMsgWhenEntrance");
        stringBuffer.append(XVFSFile.PATH_SEPARATOR);
        stringBuffer.append(mo86050i("HasNewSnsMsgWhenEntrance"));
        stringBuffer.append(APLogFileUtil.SEPARATOR_LINE);
        stringBuffer.append("HasNewChatMsgWhenExit");
        stringBuffer.append(XVFSFile.PATH_SEPARATOR);
        stringBuffer.append(mo86050i("HasNewChatMsgWhenExit"));
        stringBuffer.append(APLogFileUtil.SEPARATOR_LINE);
        stringBuffer.append("StartBrowseSnsObjectId");
        stringBuffer.append(XVFSFile.PATH_SEPARATOR);
        stringBuffer.append(mo86050i("StartBrowseSnsObjectId"));
        stringBuffer.append(APLogFileUtil.SEPARATOR_LINE);
        stringBuffer.append("EndBrowseSnsObjectId");
        stringBuffer.append(XVFSFile.PATH_SEPARATOR);
        stringBuffer.append(mo86050i("EndBrowseSnsObjectId"));
        stringBuffer.append(APLogFileUtil.SEPARATOR_LINE);
        stringBuffer.append("NextBrowseSnsObjectId");
        stringBuffer.append(XVFSFile.PATH_SEPARATOR);
        stringBuffer.append(mo86050i("NextBrowseSnsObjectId"));
        stringBuffer.append(APLogFileUtil.SEPARATOR_LINE);
        stringBuffer.append("HasNewFeedInServer");
        stringBuffer.append(XVFSFile.PATH_SEPARATOR);
        stringBuffer.append(mo86050i("HasNewFeedInServer"));
        stringBuffer.append(APLogFileUtil.SEPARATOR_LINE);
        stringBuffer.append("BrowseBrandUrlFeedCount");
        stringBuffer.append(XVFSFile.PATH_SEPARATOR);
        stringBuffer.append(mo86050i("BrowseBrandUrlFeedCount"));
        stringBuffer.append(APLogFileUtil.SEPARATOR_LINE);
        stringBuffer.append("BrowseNotBrandUrlFeedCount");
        stringBuffer.append(XVFSFile.PATH_SEPARATOR);
        stringBuffer.append(mo86050i("BrowseNotBrandUrlFeedCount"));
        stringBuffer.append(APLogFileUtil.SEPARATOR_LINE);
        stringBuffer.append("BrowseTextFeedCount");
        stringBuffer.append(XVFSFile.PATH_SEPARATOR);
        stringBuffer.append(mo86050i("BrowseTextFeedCount"));
        stringBuffer.append(APLogFileUtil.SEPARATOR_LINE);
        stringBuffer.append("BrowseImageFeedCount");
        stringBuffer.append(XVFSFile.PATH_SEPARATOR);
        stringBuffer.append(mo86050i("BrowseImageFeedCount"));
        stringBuffer.append(APLogFileUtil.SEPARATOR_LINE);
        stringBuffer.append("BrowseSightFeedCount");
        stringBuffer.append(XVFSFile.PATH_SEPARATOR);
        stringBuffer.append(mo86050i("BrowseSightFeedCount"));
        stringBuffer.append(APLogFileUtil.SEPARATOR_LINE);
        stringBuffer.append("BrowseAdFeedCount");
        stringBuffer.append(XVFSFile.PATH_SEPARATOR);
        stringBuffer.append(mo86050i("BrowseAdFeedCount"));
        stringBuffer.append(APLogFileUtil.SEPARATOR_LINE);
        stringBuffer.append("BrowseMusicFeedCount");
        stringBuffer.append(XVFSFile.PATH_SEPARATOR);
        stringBuffer.append(mo86050i("BrowseMusicFeedCount"));
        stringBuffer.append(APLogFileUtil.SEPARATOR_LINE);
        stringBuffer.append("contactCount");
        stringBuffer.append(XVFSFile.PATH_SEPARATOR);
        stringBuffer.append(mo86050i("contactCount"));
        stringBuffer.append(APLogFileUtil.SEPARATOR_LINE);
        stringBuffer.append("BrowseVideoFeedCount");
        stringBuffer.append(XVFSFile.PATH_SEPARATOR);
        stringBuffer.append(mo86050i("BrowseVideoFeedCount"));
        stringBuffer.append(APLogFileUtil.SEPARATOR_LINE);
        stringBuffer.append("ClickBrandUrlFeedCount");
        stringBuffer.append(XVFSFile.PATH_SEPARATOR);
        stringBuffer.append(mo86050i("ClickBrandUrlFeedCount"));
        stringBuffer.append(APLogFileUtil.SEPARATOR_LINE);
        stringBuffer.append("ClickNotBrandUrlFeedCount");
        stringBuffer.append(XVFSFile.PATH_SEPARATOR);
        stringBuffer.append(mo86050i("ClickNotBrandUrlFeedCount"));
        stringBuffer.append(APLogFileUtil.SEPARATOR_LINE);
        stringBuffer.append("ClickImageFeedCount");
        stringBuffer.append(XVFSFile.PATH_SEPARATOR);
        stringBuffer.append(mo86050i("ClickImageFeedCount"));
        stringBuffer.append(APLogFileUtil.SEPARATOR_LINE);
        stringBuffer.append("ClickSightFeedCount");
        stringBuffer.append(XVFSFile.PATH_SEPARATOR);
        stringBuffer.append(mo86050i("ClickSightFeedCount"));
        stringBuffer.append(APLogFileUtil.SEPARATOR_LINE);
        stringBuffer.append("ClickMusicFeedCount");
        stringBuffer.append(XVFSFile.PATH_SEPARATOR);
        stringBuffer.append(mo86050i("ClickMusicFeedCount"));
        stringBuffer.append(APLogFileUtil.SEPARATOR_LINE);
        stringBuffer.append("ClickVideoFeedCount");
        stringBuffer.append(XVFSFile.PATH_SEPARATOR);
        stringBuffer.append(mo86050i("ClickVideoFeedCount"));
        stringBuffer.append(APLogFileUtil.SEPARATOR_LINE);
        stringBuffer.append("BrowseOtherFeedCount");
        stringBuffer.append(XVFSFile.PATH_SEPARATOR);
        stringBuffer.append(mo86050i("BrowseOtherFeedCount"));
        stringBuffer.append(APLogFileUtil.SEPARATOR_LINE);
        stringBuffer.append("BrowserStreamVideoFeedCount");
        stringBuffer.append(XVFSFile.PATH_SEPARATOR);
        stringBuffer.append(mo86050i("BrowserStreamVideoFeedCount"));
        stringBuffer.append(APLogFileUtil.SEPARATOR_LINE);
        stringBuffer.append("ClickStreamVideoCount");
        stringBuffer.append(XVFSFile.PATH_SEPARATOR);
        stringBuffer.append(mo86050i("ClickStreamVideoCount"));
        stringBuffer.append(APLogFileUtil.SEPARATOR_LINE);
        stringBuffer.append("ClickAdFeed");
        stringBuffer.append(XVFSFile.PATH_SEPARATOR);
        stringBuffer.append(mo86050i("ClickAdFeed"));
        stringBuffer.append(APLogFileUtil.SEPARATOR_LINE);
        stringBuffer.append("BackGroundTime");
        stringBuffer.append(XVFSFile.PATH_SEPARATOR);
        stringBuffer.append(mo86050i("BackGroundTime"));
        stringBuffer.append(APLogFileUtil.SEPARATOR_LINE);
        stringBuffer.append("BrowseTimeLineTime");
        stringBuffer.append(XVFSFile.PATH_SEPARATOR);
        stringBuffer.append(mo86050i("BrowseTimeLineTime"));
        stringBuffer.append(APLogFileUtil.SEPARATOR_LINE);
        stringBuffer.append("BrowseMyAlbumTime");
        stringBuffer.append(XVFSFile.PATH_SEPARATOR);
        stringBuffer.append(mo86050i("BrowseMyAlbumTime"));
        stringBuffer.append(APLogFileUtil.SEPARATOR_LINE);
        stringBuffer.append("BrowseOtherAlbumTime");
        stringBuffer.append(XVFSFile.PATH_SEPARATOR);
        stringBuffer.append(mo86050i("BrowseOtherAlbumTime"));
        stringBuffer.append(APLogFileUtil.SEPARATOR_LINE);
        stringBuffer.append("BrowseMessageListTime");
        stringBuffer.append(XVFSFile.PATH_SEPARATOR);
        stringBuffer.append(mo86050i("BrowseMessageListTime"));
        stringBuffer.append(APLogFileUtil.SEPARATOR_LINE);
        stringBuffer.append("ClickNewPostTime");
        stringBuffer.append(XVFSFile.PATH_SEPARATOR);
        stringBuffer.append(mo86050i("ClickNewPostTime"));
        stringBuffer.append(APLogFileUtil.SEPARATOR_LINE);
        stringBuffer.append("BrowseFullScreenImageTime");
        stringBuffer.append(XVFSFile.PATH_SEPARATOR);
        stringBuffer.append(mo86050i("BrowseFullScreenImageTime"));
        stringBuffer.append(APLogFileUtil.SEPARATOR_LINE);
        stringBuffer.append("BrowseFullScreenSightTime");
        stringBuffer.append(XVFSFile.PATH_SEPARATOR);
        stringBuffer.append(mo86050i("BrowseFullScreenSightTime"));
        stringBuffer.append(APLogFileUtil.SEPARATOR_LINE);
        stringBuffer.append("BrowseMPArticleTime");
        stringBuffer.append(XVFSFile.PATH_SEPARATOR);
        stringBuffer.append(mo86050i("BrowseMPArticleTime"));
        stringBuffer.append(APLogFileUtil.SEPARATOR_LINE);
        stringBuffer.append("BrowseExternalArticleTime");
        stringBuffer.append(XVFSFile.PATH_SEPARATOR);
        stringBuffer.append(mo86050i("BrowseExternalArticleTime"));
        stringBuffer.append(APLogFileUtil.SEPARATOR_LINE);
        stringBuffer.append("BrowseAdFullScreenTime");
        stringBuffer.append(XVFSFile.PATH_SEPARATOR);
        stringBuffer.append(mo86050i("BrowseAdFullScreenTime"));
        stringBuffer.append(APLogFileUtil.SEPARATOR_LINE);
        stringBuffer.append("BrowseAdSightTime");
        stringBuffer.append(XVFSFile.PATH_SEPARATOR);
        stringBuffer.append(mo86050i("BrowseAdSightTime"));
        stringBuffer.append(APLogFileUtil.SEPARATOR_LINE);
        stringBuffer.append("BrowseAdDetailTime");
        stringBuffer.append(XVFSFile.PATH_SEPARATOR);
        stringBuffer.append(mo86050i("BrowseAdDetailTime"));
        stringBuffer.append(APLogFileUtil.SEPARATOR_LINE);
        stringBuffer.append("BrowseAdShortVideoTime");
        stringBuffer.append(XVFSFile.PATH_SEPARATOR);
        stringBuffer.append(mo86050i("BrowseAdShortVideoTime"));
        stringBuffer.append(APLogFileUtil.SEPARATOR_LINE);
        stringBuffer.append("BrowseAdLongVideoTime");
        stringBuffer.append(XVFSFile.PATH_SEPARATOR);
        stringBuffer.append(mo86050i("BrowseAdLongVideoTime"));
        stringBuffer.append(APLogFileUtil.SEPARATOR_LINE);
        stringBuffer.append("BrowseForwardAdLongVideoTime");
        stringBuffer.append(XVFSFile.PATH_SEPARATOR);
        stringBuffer.append(mo86050i("BrowseForwardAdLongVideoTime"));
        stringBuffer.append(APLogFileUtil.SEPARATOR_LINE);
        stringBuffer.append("StartBrowseTime");
        stringBuffer.append(XVFSFile.PATH_SEPARATOR);
        stringBuffer.append(mo86050i("StartBrowseTime"));
        stringBuffer.append(APLogFileUtil.SEPARATOR_LINE);
        stringBuffer.append("ClickFeedIdList");
        stringBuffer.append(XVFSFile.PATH_SEPARATOR);
        stringBuffer.append(mo86050i("ClickFeedIdList"));
        stringBuffer.append(APLogFileUtil.SEPARATOR_LINE);
        stringBuffer.append("ExposeFeedIdList");
        stringBuffer.append(XVFSFile.PATH_SEPARATOR);
        stringBuffer.append(mo86050i("ExposeFeedIdList"));
        stringBuffer.append(APLogFileUtil.SEPARATOR_LINE);
        stringBuffer.append("FavFeedIdList");
        stringBuffer.append(XVFSFile.PATH_SEPARATOR);
        stringBuffer.append(mo86050i("FavFeedIdList"));
        stringBuffer.append(APLogFileUtil.SEPARATOR_LINE);
        stringBuffer.append("ClickAlbumUserList");
        stringBuffer.append(XVFSFile.PATH_SEPARATOR);
        stringBuffer.append(mo86050i("ClickAlbumUserList"));
        stringBuffer.append(APLogFileUtil.SEPARATOR_LINE);
        stringBuffer.append("ForwardFeedIdList");
        stringBuffer.append(XVFSFile.PATH_SEPARATOR);
        stringBuffer.append(mo86050i("ForwardFeedIdList"));
        stringBuffer.append(APLogFileUtil.SEPARATOR_LINE);
        stringBuffer.append("ClickAvatarFeedIdList");
        stringBuffer.append(XVFSFile.PATH_SEPARATOR);
        stringBuffer.append(mo86050i("ClickAvatarFeedIdList"));
        stringBuffer.append(APLogFileUtil.SEPARATOR_LINE);
        stringBuffer.append("ClickNickNameFeedIdList");
        stringBuffer.append(XVFSFile.PATH_SEPARATOR);
        stringBuffer.append(mo86050i("ClickNickNameFeedIdList"));
        stringBuffer.append(APLogFileUtil.SEPARATOR_LINE);
        stringBuffer.append("ForwardToSingleChatFeedIdList");
        stringBuffer.append(XVFSFile.PATH_SEPARATOR);
        stringBuffer.append(mo86050i("ForwardToSingleChatFeedIdList"));
        stringBuffer.append(APLogFileUtil.SEPARATOR_LINE);
        stringBuffer.append("ForwardToChatRoomFeedIdList");
        stringBuffer.append(XVFSFile.PATH_SEPARATOR);
        stringBuffer.append(mo86050i("ForwardToChatRoomFeedIdList"));
        stringBuffer.append(APLogFileUtil.SEPARATOR_LINE);
        stringBuffer.append("FeedUpdateNotification");
        stringBuffer.append(XVFSFile.PATH_SEPARATOR);
        stringBuffer.append(mo86050i("FeedUpdateNotification"));
        stringBuffer.append(APLogFileUtil.SEPARATOR_LINE);
        stringBuffer.append("UnReadLikeCount");
        stringBuffer.append(XVFSFile.PATH_SEPARATOR);
        stringBuffer.append(mo86050i("UnReadLikeCount"));
        stringBuffer.append(APLogFileUtil.SEPARATOR_LINE);
        stringBuffer.append("UnReadCommentCount");
        stringBuffer.append(XVFSFile.PATH_SEPARATOR);
        stringBuffer.append(mo86050i("UnReadCommentCount"));
        stringBuffer.append(APLogFileUtil.SEPARATOR_LINE);
        stringBuffer.append("LastestUnReadFeedId");
        stringBuffer.append(XVFSFile.PATH_SEPARATOR);
        stringBuffer.append(mo86050i("LastestUnReadFeedId"));
        stringBuffer.append(APLogFileUtil.SEPARATOR_LINE);
        stringBuffer.append("UnReadMsgCount");
        stringBuffer.append(XVFSFile.PATH_SEPARATOR);
        stringBuffer.append(mo86050i("UnReadMsgCount"));
        stringBuffer.append(APLogFileUtil.SEPARATOR_LINE);
        stringBuffer.append("BrowseAdCanvasPageTime");
        stringBuffer.append(XVFSFile.PATH_SEPARATOR);
        stringBuffer.append(mo86050i("BrowseAdCanvasPageTime"));
        stringBuffer.append(APLogFileUtil.SEPARATOR_LINE);
        stringBuffer.append("BrowseForwardAdCanvasTime");
        stringBuffer.append(XVFSFile.PATH_SEPARATOR);
        stringBuffer.append(mo86050i("BrowseForwardAdCanvasTime"));
        stringBuffer.append(APLogFileUtil.SEPARATOR_LINE);
        stringBuffer.append("RedDotSource");
        stringBuffer.append(XVFSFile.PATH_SEPARATOR);
        stringBuffer.append(mo86050i("RedDotSource"));
        stringBuffer.append(APLogFileUtil.SEPARATOR_LINE);
        stringBuffer.append("EnterObjectId");
        stringBuffer.append(XVFSFile.PATH_SEPARATOR);
        stringBuffer.append(mo86050i("EnterObjectId"));
        stringBuffer.append(APLogFileUtil.SEPARATOR_LINE);
        stringBuffer.append("like_feed_count");
        stringBuffer.append(XVFSFile.PATH_SEPARATOR);
        stringBuffer.append(mo86050i("like_feed_count"));
        stringBuffer.append(APLogFileUtil.SEPARATOR_LINE);
        stringBuffer.append("comment_feed_count");
        stringBuffer.append(XVFSFile.PATH_SEPARATOR);
        stringBuffer.append(mo86050i("comment_feed_count"));
        stringBuffer.append(APLogFileUtil.SEPARATOR_LINE);
        stringBuffer.append("next_page_count");
        stringBuffer.append(XVFSFile.PATH_SEPARATOR);
        stringBuffer.append(mo86050i("next_page_count"));
        stringBuffer.append(APLogFileUtil.SEPARATOR_LINE);
        stringBuffer.append("BrowseMuiscPlayerFeedCount");
        stringBuffer.append(XVFSFile.PATH_SEPARATOR);
        stringBuffer.append(mo86050i("BrowseMuiscPlayerFeedCount"));
        stringBuffer.append(APLogFileUtil.SEPARATOR_LINE);
        stringBuffer.append("ClickMuiscPlayerFeedCount");
        stringBuffer.append(XVFSFile.PATH_SEPARATOR);
        stringBuffer.append(mo86050i("ClickMuiscPlayerFeedCount"));
        stringBuffer.append(APLogFileUtil.SEPARATOR_LINE);
        stringBuffer.append("MusicPlayerFeedTime");
        stringBuffer.append(XVFSFile.PATH_SEPARATOR);
        stringBuffer.append(mo86050i("MusicPlayerFeedTime"));
        stringBuffer.append(APLogFileUtil.SEPARATOR_LINE);
        stringBuffer.append("BrowseClickFinderFeedCnt");
        stringBuffer.append(XVFSFile.PATH_SEPARATOR);
        stringBuffer.append(mo86050i("BrowseClickFinderFeedCnt"));
        stringBuffer.append(APLogFileUtil.SEPARATOR_LINE);
        stringBuffer.append("FinderFeedTime");
        stringBuffer.append(XVFSFile.PATH_SEPARATOR);
        stringBuffer.append(mo86050i("FinderFeedTime"));
        stringBuffer.append(APLogFileUtil.SEPARATOR_LINE);
        stringBuffer.append("ClickFinderFeedCnt");
        stringBuffer.append(XVFSFile.PATH_SEPARATOR);
        stringBuffer.append(mo86050i("ClickFinderFeedCnt"));
        return stringBuffer.toString();
    }
}
